name: Build linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    
    runs-on: ubuntu-latest

    steps:

    # Cache Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
         version: 5.15.0
         target: desktop
         host: linux
         dir: ../Qt 
         cached: ${{ steps.cache-qt.outputs.cache-hit }}

    # Checkout dlt-viewer's revision 2.20.
    - name: Checkout of the dlt-viewer
      uses: actions/checkout@v2
      with:
        repository: GENIVI/dlt-viewer
        ref: v2.20.0

    # Checkout DLT-Message-Analyzer's revision, which is pushed
    - name: Checkout of the DLT-Message-Analyzer
      uses: actions/checkout@v2
      with:
        repository: svlad-90/DLT-Message-Analyzer
        path: ./plugin/DLT-Message-Analyzer
        ref: ${{ github.ref }}
        
    # Adjust dlt-viewer's CMake file to sub-include DLT-Message-Analyzer
    - name: Patch dlt-viewer's CMakeLists.txt
      run: echo 'add_subdirectory(DLT-Message-Analyzer/dltmessageanalyzerplugin/src)' >> CMakeLists.txt
      shell: bash
      working-directory: ./plugin

    # Create build directory
    - name: Creation of the "./build" directory
      run: mkdir ../build
      shell: bash
      working-directory: ./

    # CMake for dlt-viewer, including the DLT-Message_analyzer plugin
    - name: CMake
      run: cmake ../DLT-Message-Analyzer
      shell: bash
      working-directory: ../build
    
    # Build of the project
    - name: Make
      run: make -j8
      shell: bash
      working-directory: ../build
